export const INSUMO_SERVICE = 'INSUMO_SERVICE';
export const PRESUPUESTO_SERVICE = 'PRESUPUESTO_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const STORAGE_SERVICE = 'STORAGE_SERVICE';
